In [2]:
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd

In [ ]:
# biblioteca parecida com o numpy, mas cria tabelas com varios tipos de dados, 
# mas integrada com o mundo real

In [ ]:
# dados CSV
df = pd.read_csv('https://pycourse.s3.amazonaws.com/temperature.csv')
display(df)

In [ ]:
# dados EXCEl
arquivo_excel = pd.ExcelFile('https://pycourse.s3.amazonaws.com/temperature.xlsx')
display(arquivo_excel) # tipo Io do pandas, porque o excel possui duas plandas

df2 = pd.read_excel(arquivo_excel, sheet_name='Sheet1')
# vai salvar a primeira planilha
display(df2)

In [ ]:
#dados numericos com separador decimal = ','
df3 = pd.read_excel(arquivo_excel, sheet_name='Sheet2') #decimal=',') 
# indica virgula como separador
display(df3)

In [ ]:
# vizualindo as primeiras n linhas
n = 3
df.head(n)

# vizualizando as ultimas n linhas
df.tail(n)

In [25]:
# verificar os tipos de dados do Dataframe
df.dtypes

date               object
temperatura       float64
classification     object
dtype: object

In [24]:
# estatisticas basicas do dados
df.describe()

       temperatura
count     6.000000
mean     26.800000
std       4.075782
min      20.000000
25%      25.000000
50%      28.250000
75%      28.950000
max      31.200000

In [27]:
# dataframe info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            6 non-null      object
 1   temperatura     6 non-null      float64
 2   classification  6 non-null      object
dtypes: float64(1), object(2)
memory usage: 272.0+ bytes

In [29]:
# nome das colunas
df.columns # vizualiza os nomes
df.columns = ['chave 1', 'chave 2', 'chave 2'] #renomeia
df.columns

Index(['chave 1', 'chave 2', 'chave 2'], dtype='object')